#add  this to .bashrc


VERTEXDIR=~/src/vertex


#if [ -d /usr -a -r ~/src/vertex/scripts/bash_aliases ]; then
#    source ~/src/vertex/scripts/bash_aliases
#fi


#add to .ssh/config file

#Host pi
#   for z lab
#	Hostname 192.168.0.122
#	Port 22
#	User pi
#	IdentityFile ~/src/vertex/admin/ssh/id_vertex



MACHINE_NAME=`uname -n`
OS=`uname -s` 
OS_VER=`uname -r`
MACHINE=`uname -m`




THIS_DIR=$VERTEXDIR/scripts

SSHKEYDIR=$THIS_DIR/../admin/ssh

VRCFILE=$THIS_DIR/bash_aliases


BOXDIR=~/boxSync


PATH="${VERTEXDIR}/scripts:${PATH}"
export PATH




alias cdbs="cd $BOXDIR"
alias cdsrc='cd ~/src'
alias vup='cdv; gpull master; cd -'


# aliases for directories:


if [ $OS = 'Linux' ]; then

    if [ -z "$SSH_AGENT_PID" ]; then
        eval `ssh-agent`
    fi
fi


if [ -d /usr -a -r $SSHKEYDIR/id_vertex ]; then

    key=`ssh-add -L | grep id_vertex`
    if [ -z "$key" ] ; then
        `chmod 600 $SSHKEYDIR/id_vertex`
        `ssh-add -t 52w $SSHKEYDIR/id_vertex`
    fi
fi





#---------  GIT STUFF  ----------------

alias gpull='git pull origin'
alias gpush='git push origin'
alias gitreset='git reset --hard HEAD'



#git commands
alias githelp='open http://www.kernel.org/pub/software/scm/git/docs/user-manual.html#resolving-a-merge'


#project aliases
alias cdv='cd $VERTEXDIR'
alias pdr='ssh -Y pi pdextended'
#alias kpdr='ssh pi killall pdextended'


#other

alias latest='ls -lt | head'

if [ $OS = 'Linux' ]; then
	alias edit='leafpad'
fi


echo sourced $THIS_DIR/bash_aliases


